version: '3.3'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
    - foodgram_pg_data:/var/lib/postgresql/data
  backend:
    image: kritohanzo/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - foodgram_static:/backend_static/
      - foodgram_media:/app/media
  frontend:
    image: kritohanzo/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static/
  nginx:
    image: kritohanzo/foodgram_nginx
    ports:
      - 8000:80
    volumes:
      - foodgram_static:/usr/share/nginx/html/
      - foodgram_media:/media