### 
# ↓ USER SIDE REQUESTS ↓
### 

GET http://127.0.0.1:8000/api/users/

###

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "username": "test",
    "email": "test@mail.ru",
    "first_name": "test",
    "last_name": "testov",
    "password": "arbuz123"
}

###

GET http://127.0.0.1:8000/api/users/1/
Authorization: Token c15ed6d70f85c72ff494ce144c3c1b88079eafa1


###

GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 29308ae9507e831c06183073a6aa00ecb1b3e1c8

###

POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token c15ed6d70f85c72ff494ce144c3c1b88079eafa1
Content-Type: application/json

{
    "new_password": "arbuz123",
    "current_password": "arbuz1234"
}

###

POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "test@mail.ru",
    "password": "arbuz123"
}

###

POST http://127.0.0.1:8000/api/auth/token/logout/
Authorization: Token 29308ae9507e831c06183073a6aa00ecb1b3e1c8

### 
# ↓ SUBSCRIBE SIDE REQUESTS ↓
### 

GET http://127.0.0.1:8000/api/users/subscriptions/
Authorization: Token 2c208bf886d6422d50498d1b45146ebd74cee716

###

POST http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 2c208bf886d6422d50498d1b45146ebd74cee716

###

DELETE http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 2c208bf886d6422d50498d1b45146ebd74cee716

### 
# ↓ TAGS SIDE REQUESTS ↓
### 

GET http://127.0.0.1:8000/api/tags/

### 

GET http://127.0.0.1:8000/api/tags/1/

###

POST http://127.0.0.1:8000/api/tags/

###

PUT http://127.0.0.1:8000/api/tags/

###

PATCH http://127.0.0.1:8000/api/tags/

###

DELETE http://127.0.0.1:8000/api/tags/

### 
# ↓ INGREDIENTS SIDE REQUESTS ↓
### 

GET http://127.0.0.1:8000/api/ingredients/?name=аб

### 

GET http://127.0.0.1:8000/api/ingredients/1/

###

POST http://127.0.0.1:8000/api/ingredients/

###

PUT http://127.0.0.1:8000/api/ingredients/

###

PATCH http://127.0.0.1:8000/api/ingredients/

###

DELETE http://127.0.0.1:8000/api/ingredients/

###
# ↓ RECIPES SIDE REQUESTS ↓
### 

GET http://127.0.0.1:8000/api/recipes/
Authorization: token 00f0ada5463f7cc01569583c3549a3c832c5fa64


###

POST http://127.0.0.1:8000/api/recipes/
Authorization: token 00f0ada5463f7cc01569583c3549a3c832c5fa64
Content-Type: application/json

{
    "name": "кирилл под шубой",
    "text": "Жоский салат",
    "tags": [
        2,
        3
    ],
    "ingredients": [
        {
            "id": 748,
            "amount": 20
        },
        {
            "id": 753,
            "amount": 20
        }
    ],
    "cooking_time": 45
}

###

PUT http://127.0.0.1:8000/api/recipes/6/
Authorization: token 00f0ada5463f7cc01569583c3549a3c832c5fa64
Content-Type: application/json

{
    "name": "кирилл под шубой",
    "text": "Жоский салат",
    "cooking_time": 45
}

###

PATCH http://127.0.0.1:8000/api/recipes/4/
Authorization: token 00f0ada5463f7cc01569583c3549a3c832c5fa64
Content-Type: application/json

{
    "name": "кирилл под шубой",
    "text": "Жоский салат",
    "tags": [
        2,
        3
    ],
    "ingredients": [
        {
            "id": 748,
            "amount": 20
        },
        {
            "id": 753,
            "amount": 20
        }
    ],
    "cooking_time": 45
}