# Generated by Django 3.2 on 2023-07-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230715_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
