# Generated by Django 3.2 on 2023-07-22 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_alter_favorite_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="amount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Количество должно быть больше 0"
                    )
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Время приготовления должно быть больше 0"
                    )
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.IngredientRecipe",
                to="recipes.Ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                through="recipes.TagRecipe",
                to="recipes.Tag",
                verbose_name="Теги",
            ),
        ),
    ]
