# Generated by Django 3.2 on 2023-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
    ]
