# Generated by Django 3.2 on 2023-07-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0015_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to="", verbose_name="Картинка"
            ),
        ),
    ]
